---
title: "Ugalde_randforest_reg"
author: "Axela Keeza T. Ugalde"
date: "`r Sys.Date()`"
output: html_document
---

# Activity 13 - Ensemble Learning: Random Forest {.tabset .tabset-fade .tabset-pills}
  
## Data Preparation
```{r setup, echo = TRUE, warning = TRUE, fig.align = "center"}

library(dplyr)
library(ggplot2)
library(tidyverse)
library(ranger)
library(rpart)
library(rpart.plot)

# Read CSV
my_data <- read.csv("call_data_12October2025.csv")

# Clean the data by removing NA
clean_data <- my_data[complete.cases(my_data),]

# Countercheck if any "NA" is found
sum(is.na(clean_data))

# Remove first column
frog_data <- clean_data[ , -1]

# Response variable
frog_data$Species <- as.factor(frog_data$Species)

# Cartesian grid
hyperP_grid <- expand.grid(
  mtry = seq(2, ncol(frog_data) -1, by = 2),
  node_size = c(1,3,5),
  sample_fraction = c(0.632, 0.80),
  # placeholder
  oob_error = 0 
)

# For loop
for( i in 1:nrow(hyperP_grid)){
  model <- ranger(
    formula = Species~.,
    data = frog_data,
    num.trees = 100,
    mtry = hyperP_grid$mtry[i],
    min.node.size = hyperP_grid$node_size[i],
    sample.fraction = hyperP_grid$sample_fraction[i],
    seed = 123
  )
  hyperP_grid$oob_error[i] <- model$prediction.error
}

# Best parameter
best_para <- hyperP_grid |> arrange(oob_error) |> head(1)
best_para

# Re-run
optperm_model <- ranger(
  formula = Species~.,
  data = frog_data,
  num.trees = 500,
  mtry = best_para$mtry,
  min.node.size = best_para$node_size,
  sample.fraction = best_para$sample_fraction,
  importance = "permutation",
  probability = TRUE,
  seed = 123
)
optperm_model

optgini_model <- ranger(
  formula = Species ~ .,
  data = frog_data,
  num.trees = 500, 
  mtry = best_para$mtry,
  min.node.size = best_para$node_size,
  sample.fraction = best_para$sample_fraction,
  importance = "impurity",
  seed = 123
)
optgini_model

```

## Plot
```{r plot, echo = TRUE, warning = TRUE, fig.align = "center", fig.width = 12, fig.height = 7}

imp_perm_df <- data.frame(
  Feature    = names(optperm_model$variable.importance),
  Importance = optperm_model$variable.importance,
  Metric     = "Mean Decrease Accuracy (Permutation)"
)

imp_gini_df <- data.frame(
  Feature    = names(optgini_model$variable.importance),
  Importance = optgini_model$variable.importance,
  Metric     = "Mean Decrease Gini (Impurity)"
)

combined_imp <- rbind(imp_perm_df, imp_gini_df)

ggplot(combined_imp, aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_bar(stat = "identity", fill = "pink", width = 0.85, color = "lightgray") +
  coord_flip() +
  facet_wrap(~Metric, scales = "free_x") + 
  labs(
    title = "Variable Importance Comparison", 
    x = "Acoustic Features",
    y = "Importance Score"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(face = "bold", size = 12),
    panel.spacing = unit(3, "lines"),
    axis.text.y = element_text(size = 10)
  )

# Tree
rep_tree <- rpart(Species ~ ., data = frog_data, method = "class")
rpart.plot(rep_tree, 
           main = "Representative Decision Tree Structure for Frog Species",
           box.palette = "RdYlGn", 
           shadow.col = "gray", 
           nn = TRUE)
```