---
title: "Ugalde-gis"
author: "Axela Keeza T. Ugalde"
date: "`r Sys.Date()`"
output: html_document
---
# Activity 10 - Geographic Information System: Creating Your First Map {.tabset .tabset-fade .tabset-pills}
  
## A. Retrieving spatial data
```{r setup, echo = TRUE, warning = TRUE, fig.align = "center"}
library(sf)
library(terra)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(tidyverse)

# Read CSV
my_data <- read.csv("occurrence-Brachymeles tridactylus.csv")

# Clean and Subset
clean_data <- my_data |>
  filter(!is.na(decimalLatitude) & !is.na(decimalLongitude))

lizard_sf <- st_as_sf(clean_data, 
                      coords = c("decimalLongitude","decimalLatitude"), 
                      crs = 4326)

# Load Provincial Boundaries
ph_provinces <- st_read("PHL_adm1.shp")
ph_provinces <- st_transform(ph_provinces, 4326)
ph_provinces <- st_make_valid(ph_provinces)

# Gets all location with lizards without cutting landmass
liz_prov <- st_join(lizard_sf, ph_provinces, join = st_intersects)
prov_w_liz <- unique(liz_prov$NAME_1)
all_prov <- unique(c(prov_w_liz,"Aklan", "Antique", "Capiz", "Iloilo", "Negros Occidental", "Negros Oriental", "Romblon"))
target_provinces <- ph_provinces |>
  filter(NAME_1 %in% all_prov)

# Elevation
phil_dem <- rast("ph_ strm_geo.tif")

if (st_crs(target_provinces) != st_crs(phil_dem)) {
  target_provinces <- st_transform(target_provinces, st_crs(phil_dem))
}
dem_clipped <- crop(phil_dem, target_provinces) |> mask(target_provinces)
dem_df <- as.data.frame(dem_clipped, xy = TRUE)
colnames(dem_df) <- c("x", "y", "elevation")

plot(dem_clipped)
```


## B. Map
```{r map, echo = TRUE, warning = TRUE, fig.align = "center"}
ggplot() +
  geom_tile(data = dem_df, aes(x = x, y = y, fill = elevation)) +
  scale_fill_gradientn(colors = 
                         c("#2b83ba", "#abdda4", "#ffffbf", "#fdae61", "#d7191c"), 
                       name = "Elevation (m)") +
  geom_sf(data = target_provinces, fill = NA, color = "black", linewidth = 0.4) +
  geom_point(
    data = clean_data, 
    aes(x = decimalLongitude, y = decimalLatitude), 
    shape = 21, 
    fill = "hotpink", 
    color = "black", 
    size = 2.5, 
    stroke = 0.8) +
  coord_sf() + 
  labs(title = 
         expression(paste("Distribution of ", italic("Brachymeles tridactylus"))),
       subtitle = "Negros and Panay Islands, Philippines",
       x = "Longitude (°E)", y = "Latitude (°N)") +
  theme_linedraw() +
  theme(
    panel.grid.major = element_line(color = "gray90", linetype = "dashed"),
    plot.title = element_text(face = "bold"),
    panel.background = element_rect(fill = "aliceblue"))

ggsave("lizard_distribution_map.pdf", width = 8, height = 10, units = "in", dpi = 300)

```